# Site settings
title: RPG制作大师授权素材推广计划

# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  RPG Maker free material website share project.
baseurl: "/rmproject/" # the subpath of your site, e.g. /blog/
url: "http://miaowm5.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

permalink: none

gems:
  - jemoji
  - jekyll-sitemap

defaults:
  -
    scope:
      path: ""
    values:
      layout: default

rules:
  -
    name: 基本规则
    rules:
      -
        name: 基本规则
        url: "http://rmtemp.lofter.com/post/3e26fe_156e50a"
  -
    name: 与素材作者有关的相关规定
    rules:
      -
        name: 需要署名
        url: "http://rmtemp.lofter.com/post/3e26fe_156e50f"
      -
        name: 不需要署名
        url: "http://rmtemp.lofter.com/post/3e26fe_156e513"
      -
        name: 不需要下载报告
        url: "http://rmtemp.lofter.com/post/3e26fe_40beac5"
      -
        name: 不需要使用报告
        url: "http://rmtemp.lofter.com/post/3e26fe_40beacb"
      -
        name: 不需要报告
        url: "http://rmtemp.lofter.com/post/3e26fe_156f16f"
      -
        name: 需要下载报告
        url: "http://rmtemp.lofter.com/post/3e26fe_156e526"
      -
        name: 需要使用报告
        url: "http://rmtemp.lofter.com/post/3e26fe_156e52c"
  -
    name: 对于游戏类型的相关规定
    rules:
      -
        name: 自由地用于收费游戏中（同人游戏）
        url: "http://rmtemp.lofter.com/post/3e26fe_156e531"
      -
        name: 自由地用于收费游戏中（商业游戏）
        url: "http://rmtemp.lofter.com/post/3e26fe_156f10d"
      -
        name: 自由地用于收费游戏中（游戏类型未说明）
        url: "http://rmtemp.lofter.com/post/3e26fe_167cd74"
      -
        name: 自由地用于共享软件中（暂时无法确定规约详情）
        url: "http://rmtemp.lofter.com/post/3e26fe_1755db2"
      -
        name: 自由地用于收费游戏中
        url: "http://rmtemp.lofter.com/post/3e26fe_16780a8"
      -
        name: 自由地用于参加比赛的游戏中
        url: "http://rmtemp.lofter.com/post/3e26fe_1678067"
      -
        name: 自由地用于特殊题材的游戏中
        url: "http://rmtemp.lofter.com/post/3e26fe_1677fd6"
      -
        name: 自由地用于任何游戏中
        url: "http://rmtemp.lofter.com/post/3e26fe_156f11b"
      -
        name: 禁止用于以营利为目的的游戏中
        url: "http://rmtemp.lofter.com/post/3e26fe_160288a"
      -
        name: 禁止用于题材不适当的游戏中
        url: "http://rmtemp.lofter.com/post/3e26fe_160285e"
      -
        name: 禁止用于商业游戏中
        url: "http://rmtemp.lofter.com/post/3e26fe_16018a5"
  -
    name: 对于游戏制作的相关规定
    rules:
      -
        name: 允许加工
        url: "http://rmtemp.lofter.com/post/3e26fe_156f131"
      -
        name: 允许在不破坏素材的情况下进行加工
        url: "http://rmtemp.lofter.com/post/3e26fe_156f136"
      -
        name: 限制使用素材的软件
        url: "http://rmtemp.lofter.com/post/3e26fe_156f12d"
  -
    name: 对于二次配布·转载的相关规定
    rules:
      -
        name: 可以自由地二次配布
        url: "http://rmtemp.lofter.com/post/3e26fe_156f1c7"
      -
        name: 加工后可发布
        url: "http://rmtemp.lofter.com/post/3e26fe_156f1ae"
      -
        name: 禁止转载·二次配布
        url: "http://rmtemp.lofter.com/post/3e26fe_167cd92"